package io.github.fvarrui.jeppetto.api.chat.completions;

/**
 * Represents a chat completion choice returned by model, based on the provided input.
 */
public class Choice {

    /**
     * The reason the model stopped generating tokens. This will be stop if the model hit a natural stop point or
     * a provided stop sequence, length if the maximum number of tokens specified in the request was reached,
     * content_filter if content was omitted due to a flag from our content filters, tool_calls if the model called
     * a tool, or function_call (deprecated) if the model called a function.
     */
    private String finishReason;

    /**
     * The index of the choice in the list of choices.
     */
    private Integer index;

    /**
     * A chat completion message generated by the model.
     */
    private AssistantMessage message;

    public String getFinishReason() {
        return finishReason;
    }

    public void setFinishReason(String finishReason) {
        this.finishReason = finishReason;
    }

    public Integer getIndex() {
        return index;
    }

    public void setIndex(Integer index) {
        this.index = index;
    }

    public AssistantMessage getMessage() {
        return message;
    }

    public void setMessage(AssistantMessage message) {
        this.message = message;
    }

    @Override
    public String toString() {
        return "Choice{" +
                "finishReason='" + finishReason + '\'' +
                ", index=" + index +
                ", message=" + message +
                '}';
    }
}
